# Environment

M: 30     # number of edge servers
N: 1000   # number of edge devices
Network_num: 3  # number of edge areas

# Training

batch_size: 512
num_ep_train: 100 # number of episodes from all agents
max_ep_length: 1000 # maximum number of steps per episode

# Miscellaneous

results_path: results