# Environment

seed: 1112

M: 30     # number of edge servers
N: 1000   # number of edge devices
area_num: 10  # number of edge areas

cloud_model: 0
# 0: OpenRaaS
# 1: traditional cloud-centric (use an area as remote cloud where only servers are deployed)
# 2: cloud-centric RaaS (microservice composition is as usual but only executed in the remote cloud area)
# 3: traditional edge (only edge servers to provide services)
# 4: edge RaaS (only edge servers act as OpenRaaS workers)
compute_at_edge: True # unused in model 1 & 2

candidates_num: 10  # shown filestore candidates number per task
task_info_num: 4    # the properties number of a task
compute_type_num: 5 # the categories number of compute workers
filestore_info_num: 3 # the properties number of a filestore worker

worker_rate: 0.2

# Training

batch_size: 512
num_ep_train: 5 # number of episodes from all agents
max_ep_length: 20000 # maximum number of steps per episode

# Miscellaneous

results_path: results
get_statistics: True
print_statistics_per_slot: False
debug_mode: 1