# Environment

M: 50     # number of edge servers
N: 1000   # number of edge devices
area_num: 10  # number of edge areas

candidates_num: 10  # shown filestore candidates number per task
task_info_num: 5    # the properties number of a task
compute_type_num: 3 # the categories number of compute workers
filestore_info_num: 3 # the properties number of a filestore worker

# Training

batch_size: 512
num_ep_train: 100 # number of episodes from all agents
max_ep_length: 1000 # maximum number of steps per episode

# Miscellaneous

results_path: results